FROM arm32v7/node:20.11.0-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install
RUN npm i -g @nestjs/cli

RUN npm run build


FROM arm32v7/node:20.11.0-alpine
WORKDIR /app


COPY --from=builder /app/dist /app/dist
COPY ./package.json ./package.json
RUN npm install --omit=dev

EXPOSE 3000

CMD npm run start:prod
